.\" Man page for DSS CCalc Manual
.TH "DSS CCalc Manual" "1" "June 19, 2024" "1.0.0" "DSS CCalc Manual"

.SH NAME
CCalc

.SH SYNOPSIS
.B ccalc
.RI [OPTION] [ARGUMENTS]

.SH DESCRIPTION
.B ccalc
is a simple program that demonstrates the structure of a man page. It includes several sections commonly found in man pages.

.SH OPTIONS
.TP
.B \-h
Show this man page.
.TP
.B \-calc <expression>
Calculate basic expressions such as with +, -, *, /, %.
.TP
.B \-sqrt <number>
find square root of a number.
.TP
.B \--version
Show version.

.SH EXAMPLES
.B ccalc
-calc 5*5
.TP
This will use -calc to give you the output/result of 5*5 which will be 25.
.TP
.B ccalc
-sqrt 4
.TP
This will use -sqrt to give you the square root of 4 which will be 2.

.SH AUTHOR
AeternusDio

.SH COPYRIGHT
Copyright \(co 2024 QUACKTECH
.br
License: ASP License V2 & MIT license
